### ISSUE TITLE
ConcurrentModificationException as Hider

### ISSUE THREAD

**Issue by rukemn** [jotoh98/treasureHunt#229]
The Hider saves the already given hints and later reuses them by iterating over them. When they are beeing iterated over the Exception occures.

Reproducible by 
- Clicking too fast on the next button or 
- Setting the time between Steps in Autoplay-Mode to an intervall too small ( .25 did it for me)

It appears that the calling Thread doesn't wait properly for the Hider to finish its computation and move. The issue could only be reproduced  under heavy computation load.

https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html

https://stackoverflow.com/questions/18448671/how-to-avoid-concurrentmodificationexception-while-removing-elements-from-arr

**Comment by 1-alex98** [comment]
Please provide the Exception....

**Comment by 1-alex98** [comment]
and the corresponding stacktrace

**Comment by 1-alex98** [comment]
Which hider so u mean

**Comment by DorianRec** [comment]
> The Hider saves the already given hints and later reuses them by iterating over them. When they are beeing iterated over the Exception occures.
> 
> Reproducible by
> 
> * Clicking too fast on the next button or
> * Setting the time between Steps in Autoplay-Mode to an intervall too small ( .25 did it for me)
> 
> It appears that the calling Thread doesn't wait properly for the Hider to finish its computation and move. The issue could only be reproduced under heavy computation load.
> 
> https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html
> 
> https://stackoverflow.com/questions/18448671/how-to-avoid-concurrentmodificationexception-while-removing-elements-from-arr

Unfortunately, I also couldn't reproduce this,
which Searcher and Hider was moved ?

**Comment by rukemn** [comment]
Bug was just reproduced on Commit 7891db57 on Hinterstrategy

Searcher:  Naive AngleSearcher
Hider: FixedTreasureHider
Engine: GameEngine (Searcher - Hider)

Gamecontrolls at 0.25sec per step

Stacktrace:

Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at com.treasure.hunt.strategy.hider.impl.GameField.adaptBoundingCircle(GameField.java:139)
	at com.treasure.hunt.strategy.hider.impl.GameField.commitPlayerMovement(GameField.java:157)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.move(StatisticalHider.java:56)
	at com.treasure.hunt.strategy.hider.impl.FixedTreasureHider.move(FixedTreasureHider.java:21)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:124)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:114)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:165)
	at com.treasure.hunt.game.GameManager.lambda$beat$14(GameManager.java:302)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

The bug occurs when the Bounding Circle is to be extended and a new Circle should be drawn. This draws computational load, since all Hints which have already been given are now reapplied.

For the bug to occur make sure the treasure has been placed outside of the green boundingcircle! (Treasure is placed at random in this commit) 

![Issue229](https://user-images.githubusercontent.com/33164303/77187728-36e86680-6ad5-11ea-9fd4-2f8b0eb8576b.png)
![Issue229 1](https://user-images.githubusercontent.com/33164303/77187731-38b22a00-6ad5-11ea-95c1-4712d9ec0946.png)

**Comment by rukemn** [comment]
fixed
