### ISSUE TITLE
Bug in MaxAreaAngularHintStrategy

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#234]
Simulating a game with NaiveAngleSearcher and MaxAreaAngularHintStrategy, i got this exception, caused by the MaxAreaAngularHintStrategy instantiating a LineString containing one point.

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Invalid number of points in LineString (found 1 - must be 0 or >= 2)
	at org.locationtech.jts.geom.LineString.init(LineString.java:82)
	at org.locationtech.jts.geom.LineString.<init>(LineString.java:72)
	at org.locationtech.jts.geom.GeometryFactory.createLineString(GeometryFactory.java:582)
	at org.locationtech.jts.geom.GeometryFactory.createLineString(GeometryFactory.java:573)
	at com.treasure.hunt.strategy.hider.impl.MaxAreaAngularHintStrategy.move(MaxAreaAngularHintStrategy.java:367)
	at com.treasure.hunt.strategy.hider.impl.MaxAreaAngularHintStrategy.move(MaxAreaAngularHintStrategy.java:34)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:124)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:114)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:168)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:261)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by rukemn** [comment]
whicht commit are you on?
since I completely refactored the MaxArea Strategy I'd recommend to just checkout the latest commit on the Hinterstrategy branch an to try and reproduce the bug there, if still existent

**Comment by DorianRec** [comment]
> whicht commit are you on?
> since I completely refactored the MaxArea Strategy I'd recommend to just checkout the latest commit on the Hinterstrategy branch an to try and reproduce the bug there, if still existent

I were on master ^^
