### ISSUE TITLE
ZipException in mass run

### ISSUE THREAD

**Issue by jotoh98** [jotoh98/treasureHunt#256]
20:33:02.687 [pool-16-thread-1] ERROR c.t.hunt.service.io.SeriesService - A run failed
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: 0.hunt
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: 0.hunt
	at com.treasure.hunt.service.io.SeriesService.lambda$writeGameManagerAndSaveStats$2(SeriesService.java:140)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 4 common frames omitted

1000 mass run on naive angle and random angle

**Comment by 1-alex98** [comment]
fixed that try with newest master
