### ISSUE TITLE
MinimumRectangleStrategy breaks HalfPlaneAdapter_FixedTreasure

### ISSUE THREAD

**Issue by rank-and-file** [jotoh98/treasureHunt#347]
Sometimes the MinimumRectangleStrategy from the branch ImprovedStrategyFromPaper (or master, when #346 gets merged) breaks the HalfPlaneAdapter_FixedTreasure:

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Operation does not support GeometryCollection arguments
	at org.locationtech.jts.geom.Geometry.checkNotGeometryCollection(Geometry.java:1803)
	at org.locationtech.jts.geom.Geometry.difference(Geometry.java:1414)
	at com.treasure.hunt.strategy.hider.impl.GameField.commitPlayerMovement(GameField.java:212)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.move(StatisticalHider.java:69)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:37)
	at com.treasure.hunt.strategy.hider.impl.HalfPlaneAdapter_FixedTreasure.move(HalfPlaneAdapter_FixedTreasure.java:15)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:126)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:116)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:178)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:275)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by DorianRec** [comment]
@bsen @rukemn is this still an issue ?
