### ISSUE TITLE
Multi run widget is not completely reset after use

### ISSUE THREAD

**Issue by 1-alex98** [jotoh98/treasureHunt#392]

**Comment by 1-alex98** [comment]
Exception in thread "JavaFX Application Thread" java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:382)
	at com.treasure.hunt.view.StatisticTableController.lambda$addColumns$10(StatisticTableController.java:160)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:593)
	at javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:646)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:539)
	at javafx.scene.control.skin.TableRowSkinBase.checkState(TableRowSkinBase.java:649)
	at javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:588)
	at javafx.scene.control.Control.computePrefHeight(Control.java:570)
	at javafx.scene.Parent.prefHeight(Parent.java:1037)
	at javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1863)
	at javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1948)
	at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1250)
	at javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
